
name:        The Establishment
tempUnit:    C

dbFile:      rpiBrewData.db
keepRows:    432000

usePushbullet: true

refreshConfig: 5.0

sensors:
    - id:               28-00043eb791ff
      name:             MLT
      heatPin:          17
      heaterEnabled:    1
      defaultSetpoint:  0.0
      alarmLL:          -0.1
      alarmHH:          100.0
      alarmTolL:        5.0
      alarmTolH:        5.0
      Kc:               44
      Ti:               165
      Td:               4.0
      Ts:               5.0
      smoothPts:        5
    
    - id:               28-00043eb000ff
      name:             Kettle
      heatPin:          23
      heaterEnabled:    1
      defaultSetpoint:  0.0
      alarmLL:          -0.1
      alarmHH:          100.0
      alarmTolL:        5.0
      alarmTolH:        5.0
      Kc:               44
      Ti:               165
      Td:               4.0
      Ts:               5.0
      smoothPts:        5

extraGPIO:
    - name: Pump 1
      outputPin: 24

