
name:        The Establishment
tempUnits:   C

dbFile:      rpiBrewData.db
keepRows:    432000

usePushbullet: false

refreshConfig: 5.0

sensors:
    - id:               28-00043eb791ff
      name:             MLT
      heatPin:          17
      heaterMode:       1
      sensorEnabled:    0
      defaultSetpoint:  22.0
      dutyCycle:        0.0
      alarmLL:          -0.1
      alarmHH:          100.0
      alarmL:           5.0
      alarmH:           5.0
      Kc:               44
      Ti:               165
      Td:               4.0
      Ts:               2.0
      record_freq:      10.0
      smoothPts:        5
    
    - id:               28-00043eb000ff
      name:             Kettle
      heatPin:          23
      heaterMode:       0
      sensorEnabled:    0
      defaultSetpoint:  0.0
      dutyCycle:        0.0
      alarmLL:          -0.1
      alarmHH:          100.0
      alarmL:           5.0
      alarmH:           5.0
      Kc:               44
      Ti:               165
      Td:               4.0
      Ts:               2.0
      record_freq:      10.0
      smoothPts:        5

extraGPIO:
    - name: Pump 1
      outputPin: 24

